### ISSUE TITLE
Align all blue CSS colors to the same as home page header image

### ISSUE THREAD

**Issue by sayanee** [notthetup/unet-blog#4]
- [ ] hyperlink `a` tag
    ![image](https://user-images.githubusercontent.com/413879/44987836-32c02b00-afbb-11e8-9b70-350a7f40b00c.png)
- [ ] social button
    ![image](https://user-images.githubusercontent.com/413879/44987936-85014c00-afbb-11e8-9757-f5258e35cede.png)
- [ ] amend the blue color everywhere else in the CSS code

**Comment by notthetup** [comment]
This issue was moved to org-arl/unet-blog#10
