### ISSUE TITLE
Add a background color for code tags

### ISSUE THREAD

**Issue by sayanee** [notthetup/unet-blog#5]
![image](https://user-images.githubusercontent.com/413879/44988008-c8f45100-afbb-11e8-99e9-e6afa8ea3c27.png)

Maybe the same yellow as [Unet stack main website](https://unetstack.net/docs.html):

![image](https://user-images.githubusercontent.com/413879/44988052-f50fd200-afbb-11e8-9c6f-122f2fdfe537.png)

**Comment by notthetup** [comment]
This issue was moved to org-arl/unet-blog#11
